### PR TITLE
Use `networkInterfaceSelector` in `loadbalancerSpec`

### LINKED ISSUE #486: Adapt missing `networkInterfaceSelector` in the `LoadbalancerSpec `of `Loadbalancer` Object
Currently, the `Loadbalancer` object is missing the `networkInterfaceSelector` field in `LoadbalancerSpec`. This omission leads to unintended behavior when a `Loadbalancer` is created by the cloud provider:

- When a `Loadbalancer` is first created without `networkInterfaceSelector`, it automatically selects all network interfaces within the associated network.
- This results in a `loadbalancerRouting` configuration that includes destinations for all `networkInterfaces`.

- If any networkInterface is later deleted, the loadbalancerRouting destinations become inconsistent, potentially leading to unexpected routing issues.

To prevent these issues, we need to introduce the networkInterfaceSelector field in LoadbalancerSpec.

**Proposed changes**:

 As per `Ironcore` API design, the `Loadbalancerspec` must have a `networkInterfaceSelector` to ensure the loadbalancing across the selected `networkInterfaces`.
-  Add `networkInterfaceSelector` field in `LoadbalancerSpec` while creating the `LoadBalancer` object, and choose the appropriate label for nic in the `cloud-provider-ironcore`

Ensure below validations via testcases
-  Ensure that `loadbalancerRouting` destinations update correctly when `networkIinterfaces` are deleted or modified.
-  Add Test validation and error handling to prevent inconsistent `loadbalancerRouting`.

### PR DESCRIPTION
**Pull request by Rohit-0505**
# Proposed Changes

- Add `networkInterfaceSelector` in `loadbalancerSpec`
- Add a flag-based approach to handle `loadbalancer` and `loadbalancerRouting` with or without `networkInterfaceSelector`
- validate the changes with testcases

Fixes #486

### CODE REVIEW

File: pkg/cloudprovider/ironcore/load_balancer.go [hunk 1]
```diff
@@ -297,9 +305,21 @@ func (o *ironcoreLoadBalancer) getLoadBalancerDestinationsForNodes(ctx context.C
 			}
 
 			// If the NetworkInterface is not part of Network we continue
-			if networkInterface.Spec.NetworkRef.Name != networkName {
```
Comment (afritzler) [inline pkg/cloudprovider/ironcore/load_balancer.go:300]: Shouldn't we keep the network check. That way we ensure that no `LoadBalancer` is cross referencing NICs from other `Networks`.

**Review by afritzler — CHANGES_REQUESTED** [review]
Thanks a lot @Rohit-0505 for the PR. Just one minor thing.

**Review by afritzler — CHANGES_REQUESTED** [review]
Btw. what should happen if I have a setup where the `NetworkInterfaces` have no `cluster` label assigned to them? I am looking at a situation e.g. where I create a bunch of `Machine` + `NetworkInterfaces` manually and then (also manually) create a `kubeadm` cluster into which I want to install the CCM into. The expected behaviour is: the CCM does ensure the external `LoadBalancer` for a `Service`.

**Comment by balpert89** [comment]
I am with Rohit on out-scoping this particular use-case with a kubeadm-spawned cluster. It is valid but should be handled in its own separate issue / PR to not block this one.

File: pkg/cloudprovider/ironcore/load_balancer.go [hunk 2]
```diff
@@ -190,18 +185,30 @@ func (o *ironcoreLoadBalancer) EnsureLoadBalancer(ctx context.Context, clusterNa
 			},
 		}
 	}
+	// If loadbalancerWithNicSelector is set to true then add NetworkInterfaceSelector to loadbalancer.SPec
+	if loadbalancerWithNicSelector {
```
Comment (balpert89) [inline pkg/cloudprovider/ironcore/load_balancer.go:189]: why not using `o.loadbalancerWithNicSelector`?

File: pkg/cloudprovider/ironcore/load_balancer.go [hunk 3]
```diff
@@ -190,18 +185,30 @@ func (o *ironcoreLoadBalancer) EnsureLoadBalancer(ctx context.Context, clusterNa
...
 		return nil, fmt.Errorf("failed to apply LoadBalancer %s for Service %s: %w", client.ObjectKeyFromObject(loadBalancer), client.ObjectKeyFromObject(service), err)
 	}
 	klog.V(2).InfoS("Applied LoadBalancer for Service", "LoadBalancer", client.ObjectKeyFromObject(loadBalancer), "Service", client.ObjectKeyFromObject(service))
 
-	klog.V(2).InfoS("Applying LoadBalancerRouting for LoadBalancer", "LoadBalancer", client.ObjectKeyFromObject(loadBalancer))
-	if err := o.applyLoadBalancerRoutingForLoadBalancer(ctx, loadBalancer, nodes); err != nil {
-		return nil, err
+	// if loadbalancerWithNicSelector is set to false then cloudProvider has to create the loadbalancerRouting
+	// if loadbalancerWithNicSelector is set to true then Ironcore will take care of creating the loadbalancerRouting
+	if !loadbalancerWithNicSelector {
```
Comment (balpert89) [inline pkg/cloudprovider/ironcore/load_balancer.go:205]: same here, why not `o.loadbalancerWithNicSelector`?

File: pkg/cloudprovider/ironcore/load_balancer.go [hunk 4]
```diff
@@ -361,23 +356,24 @@ func (o *ironcoreLoadBalancer) UpdateLoadBalancer(ctx context.Context, clusterNa
 	if err := o.ironcoreClient.Get(ctx, loadBalancerKey, loadBalancer); err != nil {
 		return fmt.Errorf("failed to get LoadBalancer %s: %w", client.ObjectKeyFromObject(loadBalancer), err)
 	}
+	if !loadbalancerWithNicSelector {
```
Comment (balpert89) [inline pkg/cloudprovider/ironcore/load_balancer.go:359]: same here, why not `o.loadbalancerWithNicSelector`?

**Review by balpert89 — CHANGES_REQUESTED** [review]

File: pkg/cloudprovider/ironcore/load_balancer.go (hunk 2 above)
Comment (Rohit-0505) [reply pkg/cloudprovider/ironcore/load_balancer.go]: Thanks, you are right. changed it

File: pkg/cloudprovider/ironcore/load_balancer.go (hunk 3 above)
Comment (Rohit-0505) [reply pkg/cloudprovider/ironcore/load_balancer.go]: changed

File: pkg/cloudprovider/ironcore/load_balancer.go (hunk 4 above)
Comment (Rohit-0505) [reply pkg/cloudprovider/ironcore/load_balancer.go]: changed

File: pkg/cloudprovider/ironcore/config.go [hunk 5]
```diff
@@ -29,11 +29,13 @@ type CloudConfig struct {
...
 
 var (
-	IroncoreKubeconfigPath string
+	IroncoreKubeconfigPath      string
+	loadbalancerWithNicSelector bool
 )
 
 func AddExtraFlags(fs *pflag.FlagSet) {
 	fs.StringVar(&IroncoreKubeconfigPath, "ironcore-kubeconfig", "", "Path to the ironcore kubeconfig.")
+	fs.BoolVar(&loadbalancerWithNicSelector, "loadbalancer-with-nicselector", true, "loadbalancerSpec with networkinterfaceSelector having networkinterfaces labeled with LabelKeyClusterName: clusterName")
```
Comment (afritzler) [inline pkg/cloudprovider/ironcore/config.go:38]: Can we use here a better flag name: `--use-nic-selector`?

File: pkg/cloudprovider/ironcore/load_balancer.go [hunk 6]
```diff
@@ -36,18 +37,20 @@ var (
...
 type ironcoreLoadBalancer struct {
-	targetClient      client.Client
-	ironcoreClient    client.Client
-	ironcoreNamespace string
-	cloudConfig       CloudConfig
+	targetClient                client.Client
+	ironcoreClient              client.Client
+	ironcoreNamespace           string
+	cloudConfig                 CloudConfig
+	loadbalancerWithNicSelector bool
```
Comment (afritzler) [inline pkg/cloudprovider/ironcore/load_balancer.go:44]: Subsequentelly I would also rename the vars.

**Review by afritzler — CHANGES_REQUESTED** [review]

File: pkg/cloudprovider/ironcore/config.go (hunk 5 above)
Comment (Rohit-0505) [reply pkg/cloudprovider/ironcore/config.go]: done

File: pkg/cloudprovider/ironcore/load_balancer.go (hunk 6 above)
Comment (Rohit-0505) [reply pkg/cloudprovider/ironcore/load_balancer.go]: done

**Review by afritzler — APPROVED** [review]

**Review by afritzler — APPROVED** [review]
