### PR TITLE
Fix potential too long LoadBalancer name

### LINKED ISSUE #457: Handle potential too long `LoadBalancer` name
**What would you like to be added**:

We currently construct the `LoadBalancer` name from the cluster and `Service` name and add a UID suffix. This might result in a name which is longer than 64 chars.

Proposed solution:
Use a `GeneratedName` or `UID` of the `Service` when creating the `LoadBalancer` resource. Add to the `LoadBalancer` resource the cluster name and `Service` name as annotations in order to "find" it when running `EnsureLoadbalancer`.

Backwards compatibility concerns:
We might want to keep backwards compatibility by first trying to get the "old" name. If that can't be find we transition to the new generated name based handling of `LoadBalancers`.

### PR DESCRIPTION
**Pull request by ushabelgur**
# Proposed Changes

- Fix potential too long LoadBalancer name by deriving loadbalancer name from Service UID
- Handle backwards compatibility by checking for existing LB object with legacy name 
- Add test case for LB with legacy name

Fixes #457

### CODE REVIEW

File: pkg/cloudprovider/ironcore/load_balancer.go [hunk 1]
```diff
@@ -68,9 +68,20 @@ func (o *ironcoreLoadBalancer) GetLoadBalancer(ctx context.Context, clusterName
...
+	nameSuffix := strings.Split(string(service.UID), "-")[0]
+	return fmt.Sprintf("%s-%s-%s", clusterName, service.Name, nameSuffix)
+}
+
 func (o *ironcoreLoadBalancer) GetLoadBalancerName(ctx context.Context, clusterName string, service *v1.Service) string {
-	cloudprovider.DefaultLoadBalancerName(service)
-	return getLoadBalancerNameForService(clusterName, service)
+	legacyLoadBalancerName := getLegacyLoadBalancerName(clusterName, service)
+	existingLoadBalancer := &networkingv1alpha1.LoadBalancer{}
+	if err := o.ironcoreClient.Get(ctx, client.ObjectKey{Namespace: o.ironcoreNamespace, Name: legacyLoadBalancerName}, existingLoadBalancer); err == nil {
```
Comment (afritzler) [inline pkg/cloudprovider/ironcore/load_balancer.go:79]: Can we catch the `NotFound` error here and set the correct UID based name? Also please ensure that all non `NotFound` errors are properly handled.

**Review by afritzler — CHANGES_REQUESTED** [review]

File: pkg/cloudprovider/ironcore/load_balancer.go (hunk 1 above)
Comment (ushabelgur) [reply pkg/cloudprovider/ironcore/load_balancer.go:79]: > Can we catch the `NotFound` error here and set the correct UID based name? Also please ensure that all non `NotFound` errors are properly handled.

In any case we cannot return error from this method as per the method signature, should we just log the error and return empty in case any other error other than `NotFound` ? but again returning empty doesn't really make sense so i was returning new name formed with service Id, and rest of the flow will handle if LB is not found even with this new name.

Comment (afritzler) [reply pkg/cloudprovider/ironcore/load_balancer.go:79]: Yes, logging the error would be great here. That way we can see if something went wrong (e.g. wrong authentication, networking issues, etc.).

The problem now is what if there is a legacy name in the cluster but we could not get it due to some networking issues? Logging the error and returning an empty string which has to be correctly handled up the call stack is of course needed.

**Review by afritzler — APPROVED** [review]
